[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

# 69 don't appear in base decks
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "if self.GAME.starting_params.no_faces and SMODS.Ranks[v.value].face then keep = false end"
position = 'after'
match_indent = true
payload = '''
if _r == 'shdwn_shitty_N' then keep = false end
'''